# Default config for univariate PatchTST
# All paths and settings are for univariate experiments

data:
  csv: compare/targets/with_all_targets.csv

model:
  in_channels: 1
  seq_len: 60
  patch_size: 12
  emb_dim: 64
  n_heads: 4
  ff_mult: 4
  n_layers: 3
  dropout: 0.3
  channel_independent: true
  out_horizon: 5

train:
  epochs: 100
  batch_size: 32
  lr: 0.0003
  weight_decay: 0.0001
  ckpt_path: checkpoints/univar/univar_patchtst.pt
  log_dir: checkpoints/logs/
  resume: false
